config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  
  get "about" => "home#about", as: :about  
  get "contact" => "home#contact", as: :contact

  devise_for :users
  resources :posts do
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user= current_user

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post=Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index

    if params[:user]
      @posts = Post.where(user: params[:user]).order("created_at DESC")
    else
       @posts = Post.all.order("created_at DESC")
    end
    @post=Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_field :bdy, id: :comment_bdy, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-3">
  <div class="actions">
    <%= f.submit "Yorum At", class:"form-action btn btn-info"  %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em> <b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/about.html.erb
<div class="row featurette">
	<div class="col-md-7">
		<h2 class="featurette-heading">About<span class="text-muted"></span></h2>
		 <hr class="featurette-divider" style=" border-top:1px solid #083972;">
		<p class="lead">Hello,<br>My name is Şevket KAPLAN. I'm Software Engineer student. I have enought to exam so I didn't used Adminpanel and User capatitation in this project.<br>Thank you look my site.</p>
	</div>
	<div class="col-md-5">
		<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="<%= asset_path( 'profile.jpg' ) %>" data-holder-rendered="true">
	</div>
</div>

app/views/home/contact.html.erb
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">
                    Contact us <small>Feel free to contact us</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                                Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="service">General Customer Service</option>
                                <option value="suggestions">Suggestions</option>
                                <option value="product">Product Support</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span> Our office</legend>
            <address>
                <strong>Fırat Univercity</strong><br>
                795 Folsom Ave, Suite 600<br>
                San Francisco, CA 94107<br>
                <abbr title="Phone">
                    P:</abbr>
                (553)-370-18-33
            </address>
            <address>
                <strong>Şevket KAPLAN</strong><br>
                <a href="mailto:#">sevketkaplan.20@gmail.com</a>
            </address>
            </form>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ders</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar'%>
	<%= render 'shared/jumbotron'%>
	<div class="container">
		<%= yield %>
	</div>

	<%= render 'shared/footer'%>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :msg %>
    <%= form.text_area :msg, id: :post_msg,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Oluştur", class:"form-control btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    <div class="container">
        <div class="row">
          <% @posts.each do |post| %>

            <div class="panel panel-default widget">

                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1">
                                    <%=image_tag post.user.image.url(:thumb) if post.user.image?%>
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                             <a href="?user=<%=post.user.id%>"> <%=post.user.name%> </a> <%=post.created_at%>
                                        </div>
                                    </div>
                                    <div class="comment-text">
                                        <%=post.title%> <br/>
                                        <%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%>
                                        <br/>
                                        <%=post.msg%>
                                    </div>
                                    <hr>
                                    <div class="action">
                                      <%= link_to '', post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                                      <%= link_to '', edit_post_path(post),class:"glyphicon glyphicon-pencil" %>
                                      <%= link_to '', post_path(post),class:"glyphicon glyphicon-hand-right" %>
                                      <hr>
                                      <div id="<%=post.id%>">
                                      <%if Like.where(user:current_user, post:post).count>0%>
                                         <%= link_to "", unlike_post_path(post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                                      <%else%>
                                         <%= link_to "", like_post_path(post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                                      <%end%>
                                      </div>
                                      <hr>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
        </div>
    </div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="panel panel-default widget">
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default widget">

    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                        <%=image_tag @post.user.image.url(:mini) if @post.user.image?%>
                    </div>
                    <div class="col-xs-10 col-md-11">
                        <div>
                            <div class="mic-info">
                                 <a href="?user=<%=@post.user.id%>"> <%=@post.user.name%> </a> <%=@post.created_at%>
                            </div>
                        </div>
                        <div class="comment-text">
                            <%=@post.title%> <br/>
                            <%=image_tag @post.image.url(:medium),class:"img img-responsive" if @post.image?%>
                            <br/>
                            <%=@post.msg%>
                        </div>
                        <hr>
                        <div class="action">
                          <%= link_to '', @post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                          <%= link_to '', edit_post_path(@post),class:"glyphicon glyphicon-pencil" %>

                          <div id="<%=@post.id%>">
                          <%if Like.where(user:current_user, post:@post).count>0%>
                             <%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                          <%else%>
                             <%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                          <%end%>
                          </div>
                        </div>
                        <hr>
                        <%=render 'comments/form'%>
                        Bunu beğenler(<%=@likeds.count%>) <br/>
                        <% @likeds.each do |l|%>
                          <%=l.user.name%>
                        <% end %>
                        <hr>
                        <div id="comments">
                        <%@comments.each do |c|%>
                         <%=image_tag c.user.image.url(:mini) if c.user.image?%> <em> <%=c.user.name%> </em> <b><%=c.bdy%> </b>    <br/>
                        <%end%>
                      </div>

                    </div>
            </li>
        </ul>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')

app/views/shared/_footer.html.erb
<hr class="featurette-divider" style=" border-top:2px solid #083972;">


<footer>
	<p style="text-align: center;">© 2017 Designing & Development by Sevket KAPLAN·  All Rights Reserved.</p>
</footer>

app/views/shared/_jumbotron.html.erb
	<div class="jumbotron">
		<div class="container">
			<h1>Welcome to My Devise&Paperclip Page</h1>
			<p>Hello , welcome to my project page. I use devise and paperclip library with bootstrap in this web site. If would you use or you dont have already account, you just click button and Sign UP. <br>
			Berfore surfing my page must login. </p>
			<%= link_to 'Sign up', new_user_registration_path, :class=>"btn btn-warning btn-lg" %>
		</div>
	</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to 'Rails Devise Project with Bootstrap',root_path , :class => 'navbar-brand navbar-left' %>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><%= link_to "Home",root_path%></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to "Blog",posts_path%></li>
				</ul>
				

	<ul class="nav navbar-nav navbar-right">
    <li> <%= link_to '', new_post_path, class:"glyphicon glyphicon-plus" %> </li>
    <li class="dropdown">
        <% if user_signed_in? %>
        <br>
              <em><%=image_tag current_user.image.url(:mini) if current_user.image?%> </em>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Çıkış", destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to "Ayarlar", edit_user_registration_path%></li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to('Giriş Yap', new_user_session_path) %></li>
           <li><%= link_to('Üye Ol', new_user_registration_path) %></li>
        <% end %>

      </li>
    </ul>
			</div><!--/.nav-collapse -->
		</div><!--/.container-fluid -->
	</nav>